services:
  mcserver:
    build:
      context: .
      args:
        - MINECRAFT_VERSION=${MINECRAFT_VERSION}
    image: open-mc-server
    restart: always
    container_name: ${CONTAINER_NAME:-open-mc-server}
    stop_grace_period: 45s
    ports:
      - "${HOST_PORT:-25565}:25565"
      - "${HOST_RCON_PORT:-25575}:25575"
      - "${HOST_BLUEMAP_PORT:-8100}:8100"
    volumes:
      - mcserver:/mcserver
      - ./deposit-box:/deposit-box
    environment:
      - MINECRAFT_VERSION=${MINECRAFT_VERSION}
      - OPERATOR_UUID=${OPERATOR_UUID}
      - OPERATOR_NAME=${OPERATOR_NAME}
      - OPERATOR_LEVEL=${OPERATOR_LEVEL}
      - OVERWRITE_EXISTING_SERVER=${OVERWRITE_EXISTING_SERVER}
      - SERVER_MOTD=${SERVER_MOTD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - DIFFICULTY=${DIFFICULTY}
      - GAMEMODE=${GAMEMODE}
      - PVP_ENABLED=${PVP_ENABLED}
      - ONLINE_MODE=${ONLINE_MODE}
      - JAVA_OPTS=${JAVA_OPTS}
      - RCON_PASSWORD=${RCON_PASSWORD:-minecraft}

  webapp:
    build:
      context: ./web-app
    image: open-mc-server-webapp
    restart: always
    container_name: ${WEB_CONTAINER_NAME:-open-mc-webapp}
    expose:
      - "8080"
    depends_on:
      - mcserver
    environment:
      - MC_HOST=mcserver
      - MC_RCON_PORT=25575
      - MC_RCON_PASSWORD=${RCON_PASSWORD:-minecraft}
      - MC_MOTD=${SERVER_MOTD}
      - MC_MAX_PLAYERS=${MAX_PLAYERS}
      - DYNMAP_URL=${DYNMAP_URL:-}
      - BLUEMAP_URL=${BLUEMAP_URL:-}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - WEB_REFRESH_INTERVAL_MS=${WEB_REFRESH_INTERVAL_MS:-1800000}

  nginx:
    build:
      context: ./nginx
    image: open-mc-server-nginx
    restart: always
    container_name: ${NGINX_CONTAINER_NAME:-open-mc-nginx}
    ports:
      - "${WEB_HTTP_PORT:-8080}:80"
      - "${WEB_HTTPS_PORT:-8443}:443"
    depends_on:
      - webapp
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

volumes:
  mcserver:
    name: ${VOLUME_NAME:-mcserver}
    external: false
