{{- if ne "false" (toString ((.Values.postgres).enabled)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omcsi.fullname" . }}-postgres
  labels:
    {{- include "omcsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "omcsi.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
{{- end }}
