server.port=8092
spring.application.name=upgrade-manager

# Logging configuration
logging.level.root=INFO
logging.level.com.openmc.upgrademanager=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
